### PR TITLE
add impulsive utility daemon

### PR DESCRIPTION
**Pull request by mlauter**

### CODE REVIEW

**Comment by lh00000000** [comment]
look s good. might be cool to change https://github.com/lh00000000/modern-utils/blob/master/productivity/motivation#L19 to use this instead.

**Comment by mlauter** [comment]
🙌

**Comment by mlauter** [comment]
wonder what happens if i try and respond to this addresses from another
email

**Comment by lh00000000** [comment]
Email happens

**Comment by mlauter** [comment]
cool just gonna sign this up for every mailing list i can think of brbbbb

**Comment by lh00000000** [comment]
Every Hamilton ticket giveaway ever? This change has no conflicts with the master branch.

**Pull request merged**
